#!/usr/bin/env bash
# PreCompact checkpoint — captures session state before Claude Code compacts context.
# Without this, important decisions/blockers can be lost when context fills.
#
# Triggered by: PreCompact event (Claude Code v2.1.105+)

set -euo pipefail

PROJECT_ROOT="${CLAUDE_PROJECT_DIR:-$(pwd)}"
CHECKPOINT_DIR="$PROJECT_ROOT/production/session-state/checkpoints"
mkdir -p "$CHECKPOINT_DIR"

TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
CHECKPOINT_FILE="$CHECKPOINT_DIR/checkpoint-${TIMESTAMP}.md"

cat > "$CHECKPOINT_FILE" <<EOF
# Session checkpoint — pre-compact at $(date -Iseconds)

> Auto-generated by PreCompact hook. Context was about to be compacted; the agent
> should record key state below so it survives the compaction.

## Active task
<!-- What is the agent currently working on? -->

## Key decisions made this session
<!-- List with calibration labels: [CONFIRMED]/[LIKELY]/[UNCERTAIN] + source -->

## Blockers / open questions
<!-- What's stuck? What needs user input? -->

## Files touched
<!-- Recently modified or created files; key paths -->

## Next steps
<!-- What was the agent about to do? -->

EOF

# Symlink as latest
ln -sf "$CHECKPOINT_FILE" "$CHECKPOINT_DIR/latest.md"

echo "[pre-compact] checkpoint saved to $CHECKPOINT_FILE"
echo "[pre-compact] AGENT: please populate the checkpoint sections above before continuing."

exit 0
